### ISSUE TITLE
FpsManager.Procces Null Reference Exception

### ISSUE THREAD

**Issue by MrPeKa** [Youenn-Bouglouan/FluidWars#26]
Sometimes it shows:

> NullReferenceException: Object reference not set to an instance of an object
> Assets.Scripts.Performance.FpsManager.Process (Single currentFps) (at Assets/Scripts/Performance/FpsManager.cs:20)
> Assets.Scripts.Performance.FpsCounter.Update () (at Assets/Scripts/Performance/FpsCounter.cs:43)
>

**Comment by Youenn-Bouglouan** [comment]
Couldn't reproduce. Are you sure you're launching the game from init_scene?
