### ISSUE TITLE
Import shooting to the input manager

### ISSUE THREAD

**Issue by MrPeKa** [Youenn-Bouglouan/FluidWars#27]
Connect HoseWeapon with the PlayerController and PlayerInputHandler

**Comment by Youenn-Bouglouan** [comment]
I understand this can be closed :)?

**Comment by MrPeKa** [comment]
Not yet, we should add shooting to PlayerInputHandler as movement, camera zoom etc.

**Comment by Youenn-Bouglouan** [comment]
Oh yeah, forgot about this point, sorry.
